spring.application.name=authapp
# spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.uri=mongodb+srv://harshagarwal7983_db_user:npMfBmkdcHABMy5u@cluster0.nchwsuv.mongodb.net/authdb?retryWrites=true&w=majority